version: '3'
services:
  app:
    container_name: interior_chair_api
    build: ./go
    tty: true
    volumes:
      - ../app:/go/src/app
    ports:
      - "8080:8080"
  db:
    container_name: interior_chair_mysql
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      MYSQL_DATABASE: interior_chair_dev
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ../db/data:/var/lib/mysql
      - ../db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
